### ISSUE TITLE
Unauthorized Domain: Please contact support.

### ISSUE THREAD

**Issue by MrOdball** [mwsrc/BetterAndroRAT#4]
There is no installation guide about it , and when i try to setup it directly on my web hosting (apache2) i got this error "Unauthorized Domain: Please contact support."

**Comment by graysuit** [comment]
@MrOdball 
Go to `Panel/reg.php` and change above lines:
```php
<?php
$allowedDomains = array("www.pizzachip.com", "pizzachip.com");

if (in_array($_SERVER['HTTP_HOST'], $allowedDomains)) {
	$validDomain = "true";
} else {
	$validDomain = "false";
}
?>
```

to
```php
<?php
    $validDomain = "true";
?>
```
